name: mapa_teste
description: "App de mapas"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_map: ^8.1.1
  geocoding: ^3.0.0
  geolocator: ^14.0.0
  google_maps_flutter: ^2.12.1
  http: ^1.4.0
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon" # Define um nome para o ícone no Android (opcional)
  ios: true # Gera ícones para iOS
  image_path: "assets/icon/icone_mapa.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/icon/